In [5]:
#Codificação variáveis categóricas (OneHotEncoder)
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

dados = {
    'cor': ['vermelho', 'azul', 'verde', 'vermelho', 'verde'],
    'tamanho':['pequeno', 'medio', 'grande', 'medio', 'grande'],
    'formato':['quadrado', 'redondo', 'quadrado', 'redondo', 'quadrado']
}
df = pd.DataFrame(dados)

#Criando estancia
encoder = OneHotEncoder()

#fazer o fit
dados_codificados = encoder.fit_transform(df[['cor','tamanho', 'formato']]).toarray()

#Criando novo dataframe para visualização
df_codificado = pd.DataFrame(dados_codificados, columns=encoder.get_feature_names_out(['cor','tamanho','formato']))
print('DataFrame original')
print(df)
print('DataFrame codificado')
df_codificado

DataFrame original
        cor  tamanho   formato
0  vermelho  pequeno  quadrado
1      azul    medio   redondo
2     verde   grande  quadrado
3  vermelho    medio   redondo
4     verde   grande  quadrado
DataFrame codificado

,cor_azul,cor_verde,cor_vermelho,tamanho_grande,tamanho_medio,tamanho_pequeno,formato_quadrado,formato_redondo
0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [10]:
#Utilizando OrdinalEncoder
#Tecnica de codificação para transformar variaveis categoricas em dados númericos, atribuindo valores ordinais as categorias
from sklearn.preprocessing import OrdinalEncoder

dados = {
    'Nome':['Leandro','Daniele','Gilberto','Roberta','Joao'],
    'Idade':[32,27,54,39,68],
    'rating_satisfacao':['Satisfeito', 'Muito Satisfeito', 'Muito Insatisfeito', 'Insatisfeito', 'Neutro']
}

df = pd.DataFrame(dados)
df

#Criando ordem de categoria
categorias = ['Muito Insatisfeito', 'Insatisfeito', 'Neutro', 'Satisfeito', 'Muito Satisfeito' ]
#Criando instancia do ordinalencoder
encoder = OrdinalEncoder(categories = [categorias])

#Codificando

df['rating_satisfacao_enconder'] = encoder.fit_transform(df[['rating_satisfacao']])

#Exibindo DataFrame modificado
df.head()

#Por fim ele praticamento adicionou a coluna rating para melhorar visualização e inseriu a nota do rating de acordo com a categoria

       Nome  Idade   rating_satisfacao  rating_satisfacao_enconder
0   Leandro     32          Satisfeito                         3.0
1   Daniele     27    Muito Satisfeito                         4.0
2  Gilberto     54  Muito Insatisfeito                         0.0
3   Roberta     39        Insatisfeito                         1.0
4      Joao     68              Neutro                         2.0

In [12]:
#Utilizando labelEncoder
#Util quando temos variaveis categoricas com diferentes categorias e precisamos converte-las em valores numericos
#para que os algoritmos de aprendizado de máquina possam processá-las. Ele atribui um número unico a cada categoria
from sklearn.preprocessing import LabelEncoder

dados= {
    'tamanho':['pequeno','medio','grande','medio','pequeno'],
    'intensidade':['fraco','medio','forte','forte','fraco'],
    'classificacao':['baixo','medio','alto','medio','baixo']
}
df = pd.DataFrame(dados)

#Exibindo dataframe original
print('DataFrame Original')
print(df)

#Criando estancia labelencoder
encoder = LabelEncoder()


#Aplicando labelencoder em cada coluna usando repetição
for coluna in df.columns:
    df[coluna] = encoder.fit_transform(df[coluna])

#Exibindo dataframe codificado
print('DataFrame Codificado')
df.head()

DataFrame Original
   tamanho intensidade classificacao
0  pequeno       fraco         baixo
1    medio       medio         medio
2   grande       forte          alto
3    medio       forte         medio
4  pequeno       fraco         baixo
DataFrame Codificado

   tamanho  intensidade  classificacao
0        2            1              1
1        1            2              2
2        0            0              0
3        1            0              2
4        2            1              1